<h1>Пользователи
    <?=
    $this->tag->linkTo($this->url->get(array(
        "for" => 'gridItemCreateForm',
        "controller" => 'users')), '<i class="fa fa-plus-circle"></i>', false)
    ?>
</h1>
<div class="edit-grid">
    <?= $this->partial('editGridSearchForm') ?>

    <?php if(!empty($grid)): ?>
        <div class="scope">
            <?php
                $this->partial('deleteConfirmationControls');

                foreach($grid->items as $row){
                    $this->partial('users/gridItem');
                }
            ?>
        </div>
        <?= $this->partial('paginator') ?>
    <?php endif; ?>
</div>