<h1>Регистрация</h1>

<div class="common-grid login form">
    <div class="row x3">
        <div class="c1">
            <?= $this->tag->form(array("sinup/do", "method" => "post")) ?>
            <?= $this->tag->hiddenField(array("_code", 'value'=>'ba4f43')) ?>
            <div class="form-row">
                <div class="form-title">Ваше имя</div>
                <div class="input">
                    <?= $this->tag->textField(array("name", 'class'=>'w100')) ?>
                </div>
            </div>
            <div class="form-row">
                <div class="form-title">E-mail</div>
                <div class="input">
                    <?= $this->tag->emailField(array("email", 'class'=>'w100')) ?>
                </div>
            </div>
            <div class="form-row">
                <div class="form-title">Пароль</div>
                <div class="input">
                    <?= $this->tag->passwordField(array("password", 'class'=>'w100')) ?>
                </div>
            </div>
            <div class="form-row">
                <div class="form-title">Повторите пароль</div>
                <div class="input">
                    <?= $this->tag->passwordField(array("_password", 'class'=>'w100')) ?>
                </div>
            </div>
            <?= $this->tag->submitButton(array('Зарегистрироваться', 'onclick'=>'return signup();', 'class'=>'buttons', 'optional'=>'Подождите...')) ?>
            <?= $this->tag->endForm() ?>
        </div>
        <div class="c1">
            <ul class="controls">
                <li><?= $this->tag->linkTo('/login', 'Войти, если уже регистрировались') ?></li>
            </ul>
        </div>
    </div>
</div>