<div class="edit-form form">
    <h1><?= $row->getTitleRu() ?></h1>
    <div class="common-grid">
        <?= $this->tag->form(array($this->router->getCurrentPath().'/save', "method" => "post")) ?>
        <div class="row x2">
            <div class="c1">
                <div class="form-row">
                    <div class="form-title">Название</div>
                    <div class="input">
                        <?= $this->tag->textField(array("title_ru", 'class'=>'w100', 'value'=>$row->getTitleRu())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title">Название на английском</div>
                    <div class="input">
                        <?= $this->tag->textField(array("title_en", 'class'=>'w100', 'value'=>$row->getTitleEn())) ?>
                    </div>
                </div>
                <div class="region-selector">
                    <div class="form-row"><i class="fa fa-spinner" style="display: inline-block"></i> подождите...</div>
                    <script language="javascript">
                        $(document).ready(function(){ showRegionSelector(<?= (($countryId = $row->getCountryId()) ? $countryId : 0).', '.(($regionId = $row->getRegionId()) ? $regionId : 0) ?>); });
                    </script>
                </div>
                <?= $this->tag->submitButton(array('Сохранить', 'onclick'=>'return saveItem();', 'class'=>'buttons', 'optional'=>'Подождите...')) ?>
            </div>
        </div>
        <?= $this->tag->endForm() ?>
    </div>
</div>