<div class="form-row">
    <div class="form-title">Регион</div>
    <div class="input">
        <?=
            $this->tag->select(array(
                'region_id',
                Regions::find(array("country_id = 1", "order" => "title_ru ASC")),
                'using' => array('region_id', 'title_ru'),
                'useEmpty' => true,
                'emptyText' => 'выберите...',
                'emptyValue' => 0,
                'value'=>$regionId
            ))
        ?>
    </div>
</div>