<div class="form-row">
    <div class="form-title">Страна</div>
    <div class="input">
        <?=
        $this->tag->select(array(
            'country_id',
            Countries::find(array('', "order" => "title_ru ASC")),
            'using' => array('country_id', 'title_ru'),
            'useEmpty' => true,
            'emptyText' => 'выберите...',
            'emptyValue' => 0,
            'onChange' => 'showRegionSelector($(this).val(), 0)',
            'value'=>$countryId
        ))
        ?>
    </div>
</div>
<? if(!empty($countryId)): ?>
<div class="form-row">
    <div class="form-title">Регион</div>
    <div class="input">
        <?=
            $this->tag->select(array(
                'region_id',
                Regions::find(array("country_id = ".$countryId, "order" => "title_ru ASC")),
                'using' => array('region_id', 'title_ru'),
                'useEmpty' => true,
                'emptyText' => 'выберите...',
                'emptyValue' => 0,
                'value'=>$regionId
            ))
        ?>
    </div>
</div>
<? endif; ?>