
    <div class="left input">
        <?=
            $this->tag->select(array(
                'r',
                Regions::find(array("country_id = 1", "order" => "title_ru ASC")),
                'using' => array('region_id', 'title_ru'),
                'useEmpty' => true,
                'emptyText' => 'выберите...',
                'emptyValue' => 0,
                'onChange' => 'this.form.submit();',
                'value'=>$this->request->get('r')
            ))
        ?>
    </div>
<?php if($this->request->get('r')): ?>
    <div class="left input">
        <?=
            $this->tag->select(array(
                'c',
                Cities::find(array('region_id = '.$this->request->get('r'), "order" => "title_ru ASC")),
                'using' => array('city_id', 'title_ru'),
                'useEmpty' => true,
                'emptyText' => 'выберите...',
                'emptyValue' => 0,
                'onChange' => 'this.form.submit();',
                'value'=>$this->request->get('c')
            ))
        ?>
    </div>
<?php endif; ?>