
<div class="left input">
    <?=
    $this->tag->select(array(
        'co',
        Countries::find(array('', "order" => "title_ru ASC")),
        'using' => array('country_id', 'title_ru'),
        'useEmpty' => true,
        'emptyText' => 'выберите...',
        'emptyValue' => 0,
        'onChange' => 'this.form.submit();',
        'value'=>$this->request->get('co')
    ))
    ?>
</div>

<?php if($this->request->get('co')): ?>
<div class="left input">
    <?=
        $this->tag->select(array(
            're',
            Regions::find(array('country_id = '.$this->request->get('co'), "order" => "title_ru ASC")),
            'using' => array('region_id', 'title_ru'),
            'useEmpty' => true,
            'emptyText' => 'выберите...',
            'emptyValue' => 0,
            'onChange' => 'this.form.submit();',
            'value'=>$this->request->get('re')
        ))
    ?>
</div>
<?php endif; ?>

<?php if($this->request->get('re')): ?>
    <div class="left input">
        <?=
            $this->tag->select(array(
                'ci',
                Cities::find(array('region_id = '.$this->request->get('re'), "order" => "title_ru ASC")),
                'using' => array('city_id', 'title_ru'),
                'useEmpty' => true,
                'emptyText' => 'выберите...',
                'emptyValue' => 0,
                'onChange' => 'this.form.submit();',
                'value'=>$this->request->get('ci')
            ))
        ?>
    </div>
<?php endif; ?>