<h1>Города
    <?=
    $this->tag->linkTo($this->url->get(array(
        "for" => "gridItemCreateForm",
        "controller" => 'cities')), '<i class="fa fa-plus-circle"></i>', false)
    ?>
</h1>
<div class="edit-grid">
    <?= $this->partial('editGridSearchForm') ?>

    <?php if(!empty($grid)): ?>
        <div class="scope">
            <?php
                foreach($grid->items as $row){
                    $this->partial('cities/gridItem');
                }
            ?>
        </div>
        <?= $this->partial('paginator') ?>
    <?php endif; ?>
</div>