<div class="edit-form form">
    <h1><?= $row->getName() ?></h1>
    <div class="common-grid">
        <?= $this->tag->form(array($this->router->getCurrentPath().'/save', "method" => "post")) ?>
        <div class="row x2">
            <div class="c1">
                <div class="form-row">
                    <div class="form-title">Название</div>
                    <div class="input">
                        <?= $this->tag->textField(array("name", 'class'=>'w100', 'value'=>$row->getName())) ?>
                    </div>
                </div>
                <div class="region-selector">
                    <div class="form-row"><i class="fa fa-spinner" style="display: inline-block"></i> подождите...</div>
                    <script language="javascript">
                        $(document).ready(function(){ showCitySelector(0, <?= $row->getCityId() ?>); });
                    </script>
                </div>
                <div class="form-row">
                    <div class="form-title">Оригинальный город</div>
                    <div class="input">
                        <?= $this->tag->textField(array("address", 'class'=>'w100', 'value'=>$row->getAddress())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title">Оригинальный адрес</div>
                    <div class="input">
                        <?= $this->tag->textField(array("address_orig", 'class'=>'w100', 'value'=>$row->getAddressOrig())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title">Описание</div>
                    <div class="input">
                        <?= $this->tag->textarea(array("summary", 'class'=>'w100', 'value'=>$row->getSummary())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title">Geo-координаты: широта и долгота</div>
                    <div class="input">
                        <?= $this->tag->textField(array("address_orig", 'class'=>'w100', 'value'=>$row->getAddressOrig())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title"><?= $this->tag->linkTo(array('http://booking.com'.$row->getUrlOrig(), 'Страница', false, 'target'=>'_blank')) ?> <i class="fa fa-share" style="display: inline-block;"></i> на сайте-источнике</div>
                    <div class="input">
                        <?= $this->tag->textField(array("url_orig", 'class'=>'w100', 'value'=>'http://booking.com'.$row->getUrlOrig())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-title">Оригинальный ID на сайте-источнике</div>
                    <div class="input">
                        <?= $this->tag->textField(array("id_orig", 'class'=>'w50', 'value'=>$row->getHotelIdOrig())) ?>
                    </div>
                </div>
                <div class="form-row">
                    <div class="input">
                        <?php
                        $prop = array('status', 'value' => 500);
                        if($row->getStatus() == 500) $prop['checked'] = 'checked';
                        echo $this->tag->checkField($prop) ;
                        ?> <label>проверено</label>
                    </div>
                </div>
                <?= $this->tag->submitButton(array('Сохранить', 'onclick'=>'return saveItem();', 'class'=>'buttons', 'optional'=>'Подождите...')) ?>
            </div>
        </div>
        <?= $this->tag->endForm() ?>
    </div>
</div>