<div id="row<?= $row->getHotelId() ?>" class="items">
    <div class="cols c1"><?= $row->getHotelId() ?></div>
    <div class="cols c2">
        <?php if($row->getStatus() == 500) echo '<i class="fa green fa-check" style="display: inline-block"></i>'; ?>
        <?php if($row->cities){ if(($row->getStatus() != 500) && ($row->cities->getTitleRu() != $row->getAddress())) echo '<i class="fa red fa-exclamation-triangle" style="display: inline-block"></i>'; } ?>
        <?= $this->tag->linkTo($this->url->get(array(
            "for" => "gridItemForm",
            "controller" => 'hotels',
            "id" => $row->getHotelId(),
        )), $row->getName(), false) ?><?php if(!empty($region)) echo ', '.$region; ?>
    </div>
</div>