<h1>Отели</h1>
<div class="edit-grid">
    <?= $this->partial('editGridSearchForm') ?>

    <?php if(!empty($grid)): ?>
        <div class="scope">
            <?php
                foreach($grid->items as $row){

                    $region = array();
                    if($part = $row->cities->getTitleRu()) $region[] = $part;
                    if($part = $row->cities->getRegionRu()) $region[] = $part;
                    $region = implode(', ', $region);

                    $this->partial('hotels/gridItem');
                }
            ?>
        </div>
        <?= $this->partial('paginator') ?>
    <?php endif; ?>
</div>