<h1>Отели
    <?=
    $this->tag->linkTo($this->url->get(array(
        "for" => "gridItemCreateForm",
        "controller" => 'hotels')), '<i class="fa fa-plus-circle"></i>', false)
    ?>
</h1>
<div class="edit-grid">
    <?= $this->partial('hotels/editGridSearchForm') ?>

    <?php if(!empty($grid)): ?>
        <div class="scope">
            <?php
                foreach($grid->items as $row){

                    $region = array();
                    if($row->cities) {
                        if ($part = $row->cities->getTitleRu()) $region[] = $part;
                        if ($part = $row->cities->getRegionRu()) $region[] = $part;
                    }

                    $region = implode(', ', $region);

                    $this->partial('hotels/gridItem');
                }
            ?>
        </div>
        <?= $this->partial('paginator') ?>
    <?php endif; ?>
</div>