<!DOCTYPE html>
<html>
<head>
	<?= $this->tag->getTitle() ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'description', 'content'=>(!empty($metaTags['description']) ? $metaTags['description'] : '')), true, false, true) ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'keywords', 'content'=>(!empty($metaTags['keywords']) ? $metaTags['keywords'] : '')), true, false, true) ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'viewport', 'content'=>'width=device-width, initial-scale=1.0'), true, false, true) ?>
	<?= $this->assets->outputCss('cssBefore') ?>
	<?= $this->assets->outputJs('jsBefore') ?>
</head>
<body>
<div class="root">
	<div class="header clearfix">
		<div class="inline logo">
			<?= $this->tag->linkTo('', $this->tag->image('img/logo.png')); ?>
		</div><?= $this->partial('userControls') ?>
	</div>
	<div class="content">
		<div class="aside">
			<?= $this->partial('nav') ?>
		</div>
		<div class="wrapper">
			<?= $this->getContent() ?>
		</div>
	</div>

</div>

<!-- Alerts container -->
<div id="ohsnap"></div>

<?= $this->assets->outputCss('cssAfter') ?>
<?= $this->assets->outputJs('jsAfter') ?>
</body>
</html>