<ul class="nav">
    <li>
        <i></i>
        <?= $this->tag->linkTo('show/countries', 'Страны') ?>
        <ul>
            <li><a href="" class="active">Subpoint</a></li>
            <li><a href="">Subpoint</a></li>
        </ul>
    </li>
    <li>
        <?= $this->tag->linkTo('show/cities', 'Города') ?>
    </li>
    <li>
        <i></i>
        <?= $this->tag->linkTo('show/hotels', 'Отели') ?>
    </li>
</ul>