<ul class="nav">
    <li>
        <i></i>
        <a href="">Point 1</a>
        <ul>
            <li><a href="" class="active">Subpoint</a></li>
            <li><a href="">Subpoint</a></li>
        </ul>
    </li>
    <li>
        <a href="">Point 2</a>
    </li>
    <li>
        <i></i>
        <a href="">Point 3</a>
        <ul>
            <li><a href="">Subpoint</a></li>
            <li><a href="">Subpoint</a></li>
        </ul>
    </li>
</ul>