<ul class="paginator clearfix">
<?php

    if($query = $this->request->getQuery()){
        unset($query['_url']);
    }

    if($grid->current > 1){

        if($grid->before > 1) $query['page'] = $grid->before; else unset($query['page']);

        $url = $this->router->getUrl($this->router->getCurrentPath(), $query);

        echo '<li>'.$this->tag->linkTo($url, 'Назад').'</li>';
    }

    if($grid->current < $grid->total_pages){

        $query['page'] = $grid->next;

        $url = $this->router->getUrl($this->router->getCurrentPath(), $query);

        echo '<li>'.$this->tag->linkTo($url, 'Вперёд').'</li>';
    }
?>
</ul>