<?php
    $users = new Users();

    if($users->isAuthorised()):
?>

    <div class="inline notifications">
        <?= $this->tag->linkTo(array('', '', 'class'=>'fa fa-bell-o')) ?>
        <?= $this->tag->linkTo('logout', 'Logout') ?>
    </div>

<?php else: ?>

    <div class="inline notifications">
        <?= $this->tag->linkTo(array('', '', 'class'=>'fa fa-bell-o')) ?>
        <?= $this->tag->linkTo('signup', 'Sign up') ?>
        <?= $this->tag->linkTo('login', 'Login') ?>
    </div>

<?php endif; ?>

<div class="inline user-controls">
    <?= $this->tag->linkTo(array('', '', 'class'=>'fa fa-cog')) ?>
</div>