<div class="common-grid">
    <div class="row x6">
        <div class="c1"><i></i></div>
        <div class="c1"><i></i></div>
        <div class="c1"><i></i></div>
        <div class="c1"><i></i></div>
        <div class="c1"><i></i></div>
        <div class="c1"><i></i></div>
    </div>
    <div class="row x2">
        <div class="c1"><i></i></div>
        <div class="c1">
            <div class="row x3">
                <div class="c1"><i></i></div>
                <div class="c1"><i></i></div>
                <div class="c1"><i></i></div>
            </div>
        </div>
    </div>
</div>